use crate::commands;
use crate::state::AppState;
use axum::{
    routing::{get, post},
    Router,
};

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/customer/search/name",
            get(commands::customer::search_customers_by_name_axum),
        )
        .route(
            "/api/customer/search/mobile",
            get(commands::customer::search_customers_by_mobile_axum),
        )
        .route(
            "/api/customer/create",
            post(commands::customer::create_customer_axum),
        )
        .route(
            "/api/customer/update",
            post(commands::customer::update_customer_axum),
        )
        .route(
            "/api/customer/get",
            get(commands::customer::get_customer_axum),
        )
        .route(
            "/api/customer/addresses",
            get(commands::customer::get_customer_addresses_axum),
        )
        .route(
            "/api/customer/logs",
            get(commands::customer::get_customer_logs_axum),
        )
        .route(
            "/api/customer/delete",
            post(commands::customer::delete_customer_axum),
        )
        .route(
            "/api/customer/reactivate",
            post(commands::customer::reactivate_customer_axum),
        )
        .route(
            "/api/customer/address/create",
            post(commands::customer::create_customer_address_axum),
        )
        .route(
            "/api/customer/address/update",
            post(commands::customer::update_customer_address_axum),
        )
        .route(
            "/api/customer/address/delete",
            post(commands::customer::delete_customer_address_axum),
        )
        .route(
            "/api/customer/address/set-default",
            post(commands::customer::set_default_customer_address_axum),
        )
        .route(
            "/api/customer/sales",
            get(commands::customer::get_sales_by_customer_id_axum),
        )
        .route(
            "/api/customer/ai-insight",
            get(commands::customer::get_customer_ai_insight_axum),
        )
        // Customer Batch Operations
        .route(
            "/api/customer/batch/search",
            get(commands::customer::search_customers_by_date_axum),
        )
        .route(
            "/api/customer/batch/dormant",
            get(commands::customer::search_dormant_customers_axum),
        )
        .route(
            "/api/customer/batch/delete",
            post(commands::customer::delete_customers_batch_axum),
        )
        .route(
            "/api/customer/batch/reactivate",
            post(commands::customer::reactivate_customers_batch_axum),
        )
        .route(
            "/api/customer/best",
            get(commands::customer::search_best_customers_axum),
        )
        .route(
            "/api/customer/batch/membership",
            post(commands::customer::update_customer_membership_batch_axum),
        )
        // Consultation / CRM (already handled in commands::...)
        .route(
            "/api/crm/consultations",
            get(commands::consultation::get_consultations_axum),
        )
        .route(
            "/api/crm/consultations/update",
            post(commands::consultation::update_consultation_axum),
        )
        .route(
            "/api/crm/consultations/delete",
            get(commands::consultation::delete_consultation_axum),
        )
        .route(
            "/api/crm/claim-targets",
            get(commands::crm::get_claim_targets_axum),
        )
        .route(
            "/api/crm/sms/send",
            post(commands::crm::send_sms_simulation_axum),
        )
        .route(
            "/api/crm/special-care",
            get(commands::crm::get_special_care_customers_axum),
        )
        .route(
            "/api/crm/rfm-analysis",
            get(commands::crm::get_rfm_analysis_axum),
        )
        .route(
            "/api/crm/update-level",
            post(commands::crm::update_customer_level_axum),
        )
        .route(
            "/api/crm/update-memo-batch",
            post(commands::customer::update_customer_memo_batch_axum),
        )
        .route(
            "/api/crm/product-associations",
            get(commands::crm::get_product_associations_axum),
        )
        .route(
            "/api/crm/repurchase",
            get(commands::crm::get_repurchase_candidates_axum),
        )
}
